// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdW2awtKT0jpp-u1aW9n4yv45xCzWgs4',
    appId: '1:871444489885:web:36648e2f319b4992825674',
    messagingSenderId: '871444489885',
    projectId: 'agronet-6603',
    authDomain: 'agronet-6603.firebaseapp.com',
    storageBucket: 'agronet-6603.appspot.com',
    measurementId: 'G-MNMQZX56EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Dy26_Lf8LeXFzdarq7iaotow-OM-Maw',
    appId: '1:871444489885:android:7dc50df39be2b310825674',
    messagingSenderId: '871444489885',
    projectId: 'agronet-6603',
    storageBucket: 'agronet-6603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF4Z-Br0UCj_0XOAZ8ugSuEujWFXc4gIM',
    appId: '1:871444489885:ios:775b5a257d483584825674',
    messagingSenderId: '871444489885',
    projectId: 'agronet-6603',
    storageBucket: 'agronet-6603.appspot.com',
    iosBundleId: 'com.example.agro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF4Z-Br0UCj_0XOAZ8ugSuEujWFXc4gIM',
    appId: '1:871444489885:ios:d7daa4b54dbb9d25825674',
    messagingSenderId: '871444489885',
    projectId: 'agronet-6603',
    storageBucket: 'agronet-6603.appspot.com',
    iosBundleId: 'com.example.agro.RunnerTests',
  );
}
